#=======================================================================
#@V@:Note: This file generated by vgen V1.02 (08:28:31 PM 18 Jan 1997).
#=======================================================================

# Reading configuration from the V Config.mk file. Only works if this directory
# is a child of the main V directory (HOMEV)
CONFIG  =       ../Config.mk
include $(CONFIG)

CC	=	g++

#HOMEV   =       $(HOME)/cpp/v
#X11INC  =       /usr/X11/include
#X11LIB  =       /usr/X11R6/lib
#LIBS    =       -lV -lXaw -lXmu -lXt -lXext -lX11
#VLibDir =       $(HOMEV)/lib/linux
oDir    =       .
Bin	=	.
DEFS	=	$(HOMEV)/includex/v/v_defs.h wlndefs.h

VPATH   =       $(HOMEV)/includex

#--------------------------------------------------------------
# Architecture dependent

# Flags for includes and libraries

CFLAGS	=	-O $(INCDIR)
#CFLAGS	=	-O -I$(X11INC) -I$(VPATH) -D__LINUX__

#LFLAGS	=	-g3 -L$(X11LIB) -L$(VLibDir)
#LFLAGS	=	-O -L$(X11LIB) -L$(VLibDir)

EXOBJS	=	$(oDir)/wlnapp.o \
		$(oDir)/wlnmdlg.o \
		$(oDir)/wlnynmdg.o \
		$(oDir)/wlncnv.o \
		$(oDir)/wlncmdw.o\
		$(oDir)/poly.o\
		$(oDir)/pwalk.o\
		$(oDir)/share.o\
		$(oDir)/wDemmdlg.o\
		$(oDir)/wlhimdlg.o\
		$(oDir)/wlnopt.o\
		$(oDir)/optmdlg.o

all:	$(Bin)/ZeroPoint

objs:	$(EXOBJS)

clean:
	rm $(EXOBJS)

$(Bin)/ZeroPoint:	$(EXOBJS) $(VLibDir)/libV.a
	$(CC) -o $@ $(LDFLAGS) $(EXOBJS) $(LIBS)

$(oDir)/wlncnv.o:	wlncnv.cpp $(DEFS) wlncnv.h wlnapp.h \
	poly.h pwalk.h 
	$(CC) -c $(CFLAGS) -o $@ $<

$(oDir)/wlnmdlg.o:	wlnmdlg.cpp $(DEFS) wlnmdlg.h wlnapp.h wlncmdw.h
	$(CC) -c $(CFLAGS) -o $@ $<

$(oDir)/share.o:	share.cpp $(DEFS) share.h wlnapp.h wlncmdw.h
	$(CC) -c $(CFLAGS) -o $@ $<

$(oDir)/wDemmdlg.o:	wDemmdlg.cpp $(DEFS) wDemmdlg.h wlnapp.h \
	genArray.h
	$(CC) -c $(CFLAGS) -o $@ $<

$(oDir)/wlhimdlg.o:	wlhimdlg.cpp $(DEFS) wlhimdlg.h wlnapp.h
	$(CC) -c $(CFLAGS) -o $@ $<

$(oDir)/wlnynmdg.o: 	wlnynmdg.cpp $(DEFS) wlnynmdg.h
	$(CC) -c $(CFLAGS) -o $@ $<

$(oDir)/wlncmdw.o:	wlncmdw.cpp $(DEFS) wlncmdw.h wlnapp.h wlnynmdg.h \
	wlncnv.h wlnmdlg.h share.h wDemmdlg.h wlhimdlg.h optmdlg.h
	$(CC) -c $(CFLAGS) -o $@ $<

$(oDir)/wlnopt.o:	wlnopt.cpp $(DEFS) wlnopt.h
	$(CC) -c $(CFLAGS) -o $@ $<

$(oDir)/optmdlg.o:	optmdlg.cpp $(DEFS) optmdlg.h wlnopt.h wlnapp.h
	$(CC) -c $(CFLAGS) -o $@ $<

$(oDir)/wlnapp.o:	wlnapp.cpp $(DEFS) wlnmdlg.h \
	wlnapp.h wlncmdw.h wlnopt.h poly.h pwalk.h wlnynmdg.h
	$(CC) -c $(CFLAGS) -o $@ $<

$(oDir)/poly.o: 	poly.cpp $(DEFS) poly.h genArray.h
	$(CC) -c $(CFLAGS) -o $@ $< 

$(oDir)/pwalk.o: 	pwalk.cpp poly.cpp pwalk.h $(DEFS) poly.h genArray.h
	$(CC) -c $(CFLAGS) -o $@ $<

polytest: pwalk.cpp poly.o pwalk.h genArray.h
	$(CC) -c $(CFLAGS) -DPOLYTEST -o polytest.o pwalk.cpp
	$(CC) $(LFLAGS) -o polytest polytest.o poly.o

