//=======================================================================
//@V@:Note: This file generated by vgen V1.04 (07:13:23 PM 31 Oct 1998).
//	optmdlg.cpp:	Source for optModalDialog class
//=======================================================================

////////////////////////////////////////////////////////////////////////////
// This file is a module in the program Zero Point, a video game program  //
// for Linux X11 and Windows.                                             //
//                                                                        //
// Copyright (C) 1996, 1997, 1998 by Enumerate Inc.                       //
//                                                                        //
// Enumerate Inc. can be contacted at enumerate@rocketmail.com            //
//                                                                        //
// This file is licensed within the terms of the GNU General Public       //
// License version 2 or later. This source code may freely redistributed  //
// or modified within the terms of that license, as described in the file //
// 'COPYING' which should be included with any redistribution of this     //
// file. If the file COPYING is not available, a copy of the General      //
// Public License can be obtained from the Free Software Foundation, Inc. //
// 675 Mass Ave., Cambridge, MA 02139.                                    //
//                                                                        //
// THIS PROGRAM IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER  //
// EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED       //
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.    //
// THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS    //
// WITH YOU.  SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF  //
// ALL NECESSARY SERVICING, REPAIR OR CORRECTION.                         //
//////////////////////////////////////////////////////////////////////////// 

#include <string.h>
#include <v/vnotice.h>
#include <v/vutil.h>
#include "wlnapp.h"    //wlnApp
#include "optmdlg.h"

//@V@:BeginIDs
enum {
  lblMainMsg = 3000,
  btnTestDlg		// add your id's here
};
//@V@:EndIds

// //@V@:BeginDialogCmd DefaultCmds
//     static DialogCmd DefaultCmds[] =
//       {
// 	{C_Label, lblMainMsg, 0,"X",NoList,CA_MainMsg,isSens,NoFrame, 0, 0},

// 	{C_Button, M_Cancel, 0, " Cancel ",NoList,CA_None,
// 	    isSens,NoFrame,0, lblMainMsg},
// 	{C_Button, M_OK, 0, " OK ", NoList, CA_DefaultButton,
// 	    isSens, NoFrame, M_Cancel, lblMainMsg},

// 	{C_Button, btnTestMDlg, 0, " Test ", NoList, CA_None,
// 	    isSens, NoFrame, M_OK, lblMainMsg},

// 	{C_EndOfList,0,0,0,0,CA_None,0,0,0}
//     };
// //@V@:EndDialogCmd
static int speedspin[3] = {miLm, maLm, 1};
static int delayspin[3] = {miDl, maDl, 1};
static int numbrspin[3] = {miNp, maNp, 1};
static int steprspin[3] = {miSp, maSp, 1};
static int livesspin[3] = {miSl, maSl, 1};

//@V@:BeginDialogCmd DefaultCmds
    static DialogCmd DefaultCmds[] =
      {
	{C_Label, lblMainMsg, 0,"Option Values",NoList,CA_MainMsg,isSens,NoFrame, 0, 0},
	
	{C_Frame, frmOptDlg, 0, "",NoList, CA_None,
	 isSens, NoFrame, 0, lblMainMsg},
	{C_Label, lblOpt1, 0, "Step Distance       ", NoList, CA_None,
	 isSens, frmOptDlg, 0, 0},
        {C_Label, lblHid1, 0, "0000", NoList, CA_Hidden,
	 notSens, frmOptDlg, lblOpt1, 0, 20},
	{C_BoxedLabel, lblOpt1a, 0, "15", NoList, CA_None,
	 isSens, frmOptDlg,lblOpt1,0,20},
	{C_Slider,optSpin1, 0, "Step Distance", NoList, 
	 CA_Horizontal, isSens, frmOptDlg, lblHid1, 0},
	{C_Label, lblOpt2, 0, "Time per Step  ", NoList, CA_None,
	 isSens, frmOptDlg, 0, optSpin1},
	{C_BoxedLabel, lblOpt2a, 0, "60", NoList, CA_None,
	 isSens, frmOptDlg, lblOpt1, optSpin1, 20},
	{C_Slider,optSpin2, 0000, "Time per step", NoList, 
	 CA_Horizontal, isSens, frmOptDlg, lblHid1, optSpin1},
	{C_Label, lblOpt3, 0, "Number of Lines", NoList, CA_None,
	 isSens, frmOptDlg, 0, optSpin2},
	{C_BoxedLabel, lblOpt3a, 0, "50", NoList, CA_None,
	 isSens, frmOptDlg, lblOpt1, optSpin2, 20},
	{C_Slider,optSpin3, 0000, "Number of Lines", NoList, 
	 CA_Horizontal, isSens, frmOptDlg, lblHid1, optSpin2},
	{C_Label, lblOpt4, 0, "Lines per Color", NoList, CA_None,
	 isSens, frmOptDlg, 0, optSpin3},
	{C_BoxedLabel, lblOpt4a, 0, "10", NoList, CA_None,
	 isSens, frmOptDlg, lblOpt1, optSpin3, 20},
	{C_Slider,optSpin4, 0000, "Lines per Color", NoList, 
	 CA_Horizontal, isSens, frmOptDlg, lblHid1, optSpin3},
	{C_Label, lblOpt7, 0, "Start Lives    ", NoList, CA_None,
	 isSens, frmOptDlg, 0, optSpin4},
	{C_BoxedLabel, lblOpt7a, 0, "5", NoList, CA_None,
	 isSens, frmOptDlg, lblOpt1, optSpin4, 20},
	{C_Slider,optSpin7, 0000, "Start Lives", NoList, 
	 CA_Horizontal, isSens, frmOptDlg, lblHid1, optSpin4},

	{C_Button, M_OK, 0, " OK ", NoList, CA_DefaultButton,
	    isSens, NoFrame, frmOptDlg, lblMainMsg},
	{C_Button, M_Cancel, 0, " Cancel ",NoList,CA_None,
	    isSens,NoFrame,frmOptDlg,M_OK},

	{C_Button, btnTestDlg, 0, " Set Defaults ", NoList, CA_None,
	 isSens, NoFrame, frmOptDlg, M_Cancel},

	{C_EndOfList,0,0,0,0,CA_None,0,0,0} 
    };
//@V@:EndDialogCmd


//======================>>> optModalDialog::optModalDialog <<<==================
  optModalDialog::optModalDialog(vBaseWindow* bw, char* title) :
    vModalDialog(bw, title)
  {
    UserDebug(Constructor,"optModalDialog::optModalDialog()\n")
    AddDialogCmds(DefaultCmds);		// add the predefined commands
  }

//===================>>> optModalDialog::~optModalDialog <<<====================
  optModalDialog::~optModalDialog()
  {
    UserDebug(Destructor,"optModalDialog::~optModalDialog() destructor\n")
  }

//====================>>> optModalDialog::optAction <<<====================
int optModalDialog::optAction(char* msg)
{
  ItemVal ans,rval;
  
  
  

  ans = ShowModalDialog(msg,rval);
  if (ans == M_Cancel)
    return 0;

// *** Add code to process dialog values here

  return ans == M_OK;
}

//====================>>> optModalDialog::DialogCommand <<<====================
void optModalDialog::DialogCommand(ItemVal id, ItemVal retval, CmdType ctype)
{
  UserDebug2(CmdEvents,"optModalDialog::DialogCommand(id:%d, val:%d)\n",id, retval)

    //     switch (id)		// We will do some things depending on value
    //       {
    // 	//@V@:Case: btnTestMDlg
    // 	case btnTestMDlg:
    // 	  {
    // 	    vNoticeDialog note(this);
    // 	    note.Notice("Test Dialog");
    // 	    break;
    // 	  }	//@V@:EndCase
    //       }
    char strTemp[256];

    switch (id)		// We will do some things depending on value
      {
	//@V@:Case: btnTestDlg
      case M_OK:
	wlnOpts::getOpts()[1] = fromSpin(1, GetValue(optSpin1));
	wlnOpts::getOpts()[2] = fromSpin(2, GetValue(optSpin2));
	wlnOpts::getOpts()[3] = fromSpin(3, GetValue(optSpin3));
	wlnOpts::getOpts()[4] = fromSpin(4, GetValue(optSpin4));
	wlnOpts::getOpts()[7] = fromSpin(7, GetValue(optSpin7));
	break;
      case btnTestDlg:  //Set defaults
	{
	  CloseDialog();
	  wlnOpts::getOpts()[1] = wlnOpts::getDefs()[1];
	  wlnOpts::getOpts()[2] = wlnOpts::getDefs()[2];
	  wlnOpts::getOpts()[3] = wlnOpts::getDefs()[3];
	  wlnOpts::getOpts()[4] = wlnOpts::getDefs()[4];
	  wlnOpts::getOpts()[7] = wlnOpts::getDefs()[7];
	  //set spinners
	  SetValue(optSpin1, toSpin(1, wlnOpts::getOpts()[1]), Value);
	  SetValue(optSpin2, toSpin(2, wlnOpts::getOpts()[2]), Value);
	  SetValue(optSpin3, toSpin(3, wlnOpts::getOpts()[3]), Value);
	  SetValue(optSpin4, toSpin(4, wlnOpts::getOpts()[4]), Value);
	  SetValue(optSpin7, toSpin(7, wlnOpts::getOpts()[7]), Value);
	  break;
	}	
      case M_Cancel:
	SetValue(optSpin1, toSpin(1, wlnOpts::getOpts()[1]), Value);
	SetValue(optSpin2, toSpin(2, wlnOpts::getOpts()[2]), Value);
	SetValue(optSpin3, toSpin(3, wlnOpts::getOpts()[3]), Value);
	SetValue(optSpin4, toSpin(4, wlnOpts::getOpts()[4]), Value);
	SetValue(optSpin7, toSpin(7, wlnOpts::getOpts()[7]), Value);
	break;
      case optSpin1:
        IntToStr(fromSpin(1, retval), strTemp);
        SetString(lblOpt1a, strTemp);
        break;
      case optSpin2:
        IntToStr(fromSpin(2, retval), strTemp);
        SetString(lblOpt2a, strTemp);
        break;
      case optSpin3:
        IntToStr(fromSpin(3, retval), strTemp);
        SetString(lblOpt3a, strTemp);
        break;
      case optSpin4:
        IntToStr(fromSpin(4, retval), strTemp);
        SetString(lblOpt4a, strTemp);
        break;
      case optSpin7:
        IntToStr(fromSpin(7, retval), strTemp);
        SetString(lblOpt7a, strTemp);
        break;
      }//switch(id)
  vModalDialog::DialogCommand(id,retval,ctype);
}

void optModalDialog::DialogDisplayed(){
  char strTemp[256];
  int  intTemp;
  
  if(((wlnApp*)theApp)->practicing()){
    SetValue(lblOpt1, false, Sensitive);
    SetValue(lblOpt1a, false, Sensitive);
    SetValue(optSpin1, false, Sensitive);
    SetValue(lblOpt2, false, Sensitive);
    SetValue(lblOpt2a, false, Sensitive);
    SetValue(optSpin2, false, Sensitive);
    SetValue(btnTestDlg, false, Sensitive);
  } else {
    SetValue(lblOpt1, true, Sensitive);
    SetValue(lblOpt1a, true, Sensitive);
    SetValue(optSpin1, true, Sensitive);
    SetValue(lblOpt2, true, Sensitive);
    SetValue(lblOpt2a, true, Sensitive);
    SetValue(optSpin2, true, Sensitive);
    SetValue(btnTestDlg, true, Sensitive);
  }
  //set the spinners to current values
  SetValue(optSpin1, toSpin(1, wlnOpts::getOpts()[1]), Value);
  IntToStr(wlnOpts::getOpts()[1], strTemp);
  SetString(lblOpt1a, strTemp);
  SetValue(optSpin2, toSpin(2, wlnOpts::getOpts()[2]), Value);
  IntToStr(wlnOpts::getOpts()[2], strTemp);
  SetString(lblOpt2a, strTemp);
  SetValue(optSpin3, toSpin(3, wlnOpts::getOpts()[3]), Value);
  IntToStr(wlnOpts::getOpts()[3], strTemp);
  SetString(lblOpt3a, strTemp);
  SetValue(optSpin4, toSpin(4, wlnOpts::getOpts()[4]), Value);
  IntToStr(wlnOpts::getOpts()[4], strTemp);
  SetString(lblOpt4a, strTemp);
  SetValue(optSpin7, toSpin(7, wlnOpts::getOpts()[7]), Value);
  IntToStr(wlnOpts::getOpts()[7], strTemp);
  SetString(lblOpt7a, strTemp);
}//DialogDisplayed  

int optModalDialog::fromSpin(int optN, int SpinVal){
  long inter;
  inter = (wlnOpts::getMaxs()[optN] - wlnOpts::getMins()[optN]);
  inter *= SpinVal;
  inter += (wlnOpts::getMins()[optN] * 100L);
  inter /= 100;
  return int(inter);
}

int optModalDialog::toSpin(int optN, int Value){
  long inter;
  inter = (Value - wlnOpts::getMins()[optN]) * 100;
  inter /= (wlnOpts::getMaxs()[optN] - wlnOpts::getMins()[optN]);
  return int(inter);
}
