//=======================================================================
//@V@:Note: This file generated by vgen V1.02 (04:22:45 PM 04 Feb 1997).
//	wlnmdlg.cpp:	Source for wlnModalDialog class
//=======================================================================

////////////////////////////////////////////////////////////////////////////
// This file is a module in the program Zero Point, a video game program  //
// for Linux X11 and Windows.                                             //
//                                                                        //
// Copyright (C) 1996, 1997, 1998 by Enumerate Inc.                       //
//                                                                        //
// Enumerate Inc. can be contacted at enumerate@rocketmail.com            //
//                                                                        //
// This file is licensed within the terms of the GNU General Public       //
// License version 2 or later. This source code may freely redistributed  //
// or modified within the terms of that license, as described in the file //
// 'COPYING' which should be included with any redistribution of this     //
// file. If the file COPYING is not available, a copy of the General      //
// Public License can be obtained from the Free Software Foundation, Inc. //
// 675 Mass Ave., Cambridge, MA 02139.                                    //
//                                                                        //
// THIS PROGRAM IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER  //
// EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED       //
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.    //
// THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS    //
// WITH YOU.  SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF  //
// ALL NECESSARY SERVICING, REPAIR OR CORRECTION.                         //
//////////////////////////////////////////////////////////////////////////// 


#include "share.h"
#include "wlncmdw.h"
#include <v/vnotice.h>
#include "wlnapp.h"

//@V@:BeginIDs
    enum {
    lblMainMsg = 1000,
    btnTestMDlg,		// add your id's here
    
  };
//@V@:EndIds

static char * startupwarn = 
"Zero Point v.0.9.4 A video game program for Linux X11 and Windows               \n\nCopyright (c) 1996, 1997, 1998, 1999 by Enumerate Inc.                          \n\nTHIS PROGRAM IS PROVIDED \"AS-IS\".  THERE IS NO WARRANTY EXPRESS OR IMPLIED OF   \nANY KIND, INCLUDING, BUT NOT LIMITED TO, ANY WARRANTY OF FITNESS OR               \nMERCHANTABILITY FOR ANY PURPOSE.  USE THIS SOFTWARE AT YOUR OWN RISK.           \n\nThis software is covered by the GNU General Public License--see the file 'COPYING'\nin the distribution, or contact the Free Software Foundation at 675 Mass Ave.,    \nCambridge, MA 02139. Any distribution of this software must include this copyright\nnotice, that file, and should include either the source code for the program or   \ninformation about how the the source code can be freely accessed. The General     \nPublic License describes the terms under which the software may be redistributed  \nand/or modified, including what notifications must be included in the modified    \nprogram.  This program was written by Tim Farnum for Enumerate Inc.             \n\nIf you have received this software without the source code or access to it, you   \nmay contact the developers at Enumerate Inc. by sending e-mail to               \n\nenumerate@rocketmail.com.                                                       \n\nThis program was developed with the V GUI toolkit, a free cross-platform C++ GUI  \nframework.  More information about the V GUI toolkit is available at            \n\nhttp://www.objectcentral.com/";

static int lSpnMinMaxStp[3] = {1,97,3}; 

//@V@:BeginDialogCmd DefaultCmds
    static DialogCmd DefaultCmds[] =
      {
	{C_Label, lblShare, 0,"X",NoList,CA_MainMsg,isSens,NoFrame, 0, 0},
	{C_Text, lblStartMsg, 0, "", startupwarn,CA_None,isSens,NoFrame,0,lblShare},
	
	{C_Frame,pLFrame, 0, "", NoList, CA_None, isSens, NoFrame, 0, lblStartMsg},
	{C_Label,pLFLabel,0,"Pick a starting Level:",NoList,CA_NoBorder,isSens, pLFrame,0,0},
	{C_Spinner,lSpinner,1,"Level",(void*)lSpnMinMaxStp,CA_None,isSens,pLFrame,pLFLabel,0},
	//	{C_Button, M_Cancel, 0, " Cancel ",NoList,CA_None,
	//  isSens,NoFrame,0, pLFrame},
	{C_Button, M_OK, 0, " Play ", NoList, CA_DefaultButton,
	    isSens, NoFrame, 0, pLFrame},
	{C_Button, btnPractice, 0, " Practice ", NoList, CA_None, isSens, 
	 NoFrame, M_OK, pLFrame},
	{C_Button, btnStartDemo, 0, " Start Demo " , NoList, CA_None, isSens,
	 NoFrame, btnPractice, pLFrame},
	{C_Button, cancelStart, 0, " Cancel ", NoList, CA_None, isSens, 
	 NoFrame, btnStartDemo, pLFrame},
	//{C_Button, btnTestMDlg, 0, " Test ", NoList, CA_None,
	//  isSens, NoFrame, M_OK, pLFrame},

	{C_EndOfList,0,0,0,0,CA_None,0,0,0}
    };
//@V@:EndDialogCmd


//======================>>> wlnShare::wlnShare <<<==================
  wlnShare::wlnShare(vBaseWindow* bw, char* title) :
    vModalDialog(bw, title)
  {
    UserDebug(Constructor,"wlnShare::wlnShare()\n")
    _myCmdWin = (wlnCmdWindow*) bw;
    AddDialogCmds(DefaultCmds);		// add the predefined commands
  }

//===================>>> wlnShare::~wlnShare <<<====================
  wlnShare::~wlnShare()
  {
    UserDebug(Destructor,"wlnShare::~wlnShare() destructor\n")
  }

//====================>>> wlnShare::wlnAction <<<====================
  int wlnShare::wlnAction(char* msg)
  {
    ItemVal ans,rval;

    ans = ShowModalDialog(msg,rval);
    if (ans == cancelStart)
	return 0;

    // *** Add code to process dialog values here
    if(ans == btnStartDemo){
      return btnStartDemo;
    }

    return ans == M_OK;
  }//wlnAction

//====================>>> wlnShare::DialogCommand <<<====================
void wlnShare::DialogCommand(ItemVal id, ItemVal retval, CmdType ctype){
  UserDebug2(CmdEvents,"wlnShare::DialogCommand(id:%d, val:%d)\n",id, retval);
  int theLevel;
  static int already = 0;
  //int i;
  //ItemVal indx;
  switch (id)		// We will do some things depending on value
    {
    case M_OK:
      //theLevel = 0;
      //indx = pickL1;
      //for(i = 0; i < 12; i++){
      //if(GetValue(pickL1 + i)){
      //theLevel = i * 3 + 1;
      //}
      //}
      theLevel = GetValue(lSpinner);
      if(!theLevel) theLevel = 1;
      ((wlnApp*)theApp)->startAtLevel(theLevel);
      break;
    case btnPractice:
      CloseDialog(); //release the dialog
      theLevel = GetValue(lSpinner);
      if(!theLevel) theLevel = 1;
      ((wlnApp*)theApp)->practiceMode(true);
      ((wlnApp*)theApp)->startAtLevel(theLevel);
      ((wlnApp*)theApp)->SetValueAll(mnuPractice, true, Checked);
      break;
    case btnTestMDlg:
      {
	vNoticeDialog note(this);
	note.Notice("Test Dialog");
	break;
      }	//@V@:EndCase
    case btnStartDemo:
      {
	CloseDialog();
	break;
      }
    case cancelStart:
      {
	((wlnApp*)theApp)->Exit();
	break;
      }
    }//end switch
  vModalDialog::DialogCommand(id,retval,ctype);
}//DialogCommand

