//=======================================================================
//@V@:Note: This file generated by vgen V1.02 (09:05:18 PM 18 Aug 1997).
//	wlhimdlg.cpp:	Source for wlnHiModalDialog class
//=======================================================================

////////////////////////////////////////////////////////////////////////////
// This file is a module in the program Zero Point, a video game program  //
// for Linux X11 and Windows.                                             //
//                                                                        //
// Copyright (C) 1996, 1997, 1998 by Enumerate Inc.                       //
//                                                                        //
// Enumerate Inc. can be contacted at enumerate@rocketmail.com            //
//                                                                        //
// This file is licensed within the terms of the GNU General Public       //
// License version 2 or later. This source code may freely redistributed  //
// or modified within the terms of that license, as described in the file //
// 'COPYING' which should be included with any redistribution of this     //
// file. If the file COPYING is not available, a copy of the General      //
// Public License can be obtained from the Free Software Foundation, Inc. //
// 675 Mass Ave., Cambridge, MA 02139.                                    //
//                                                                        //
// THIS PROGRAM IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER  //
// EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED       //
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.    //
// THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS    //
// WITH YOU.  SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF  //
// ALL NECESSARY SERVICING, REPAIR OR CORRECTION.                         //
//////////////////////////////////////////////////////////////////////////// 


#include "wlhimdlg.h"
#include <v/vnotice.h>
#include <strstream.h>
#include "wlnapp.h"    //wlnApp

//@V@:BeginIDs
    enum {
    lblMainMsg = 3500,
    btnTestMDlg		// add your id's here
  };
//@V@:EndIds

static char wlnnstr[charSz];
static char wlnlevstr[charSz];
static char wlnscostr[charSz];


//@V@:BeginDialogCmd DefaultCmds
		 static DialogCmd DefaultCmds[] =
			 {
	//{C_Label, lblMainMsg, 0,"X",NoList,CA_MainMsg,isSens,NoFrame, 0, 0},

	{C_Frame, frmHiScore, 0,"",NoList,CA_None,isSens,NoFrame, 0, 0},
	{C_Text, txtHiName, 0, "", wlnnstr,
	 CA_NoBorder, isSens, frmHiScore, 0, 0},
	{C_Text, txtHiLevel, 0, "", wlnlevstr,
	 CA_NoBorder, isSens, frmHiScore, txtHiName, 0},
	{C_Text, txtHiScore, 0, "", wlnscostr,
	 CA_NoBorder, isSens, frmHiScore, txtHiLevel, 0},

	//{C_Button, M_Cancel, 0, " Cancel ",NoList,CA_None,
	//  isSens,NoFrame,0, lblMainMsg},
	{C_Button, M_OK, 0, " OK ", NoList, CA_DefaultButton,
			isSens, NoFrame, 0, frmHiScore},

	//{C_Button, btnTestMDlg, 0, " Test ", NoList, CA_None,
	//  isSens, NoFrame, M_OK, lblMainMsg},

	{C_EndOfList,0,0,0,0,CA_None,0,0,0}
		 };
//@V@:EndDialogCmd


//======================>>> wlnHiModalDialog::wlnHiModalDialog <<<==================

	wlnHiModalDialog::wlnHiModalDialog(vBaseWindow* bw, char* title) :
		vModalDialog(bw, title)
	{
		ostrstream names(wlnnstr, charSz),
			levels(wlnlevstr, charSz),
			scores(wlnscostr, charSz);
		names << "NAME\n";
		levels << "LEVEL\n";
		scores << "SCORE\n";
		size_t n = ((wlnApp*)theApp)->getHigh().tellSize();
		size_t i;
		for(i = 0; i < n; i++){
			names << ((wlnApp*)theApp)->getHigh()[i].name << endl;
			levels << ((wlnApp*)theApp)->getHigh()[i].aLevel << endl;
			scores << ((wlnApp*)theApp)->getHigh()[i].aScore << endl;
		}
		for(i = n; i < numHi; i++){
			names << "Ron" << endl;
			levels << "13" << endl;
			scores << "way high" << endl;
		}
		names << ends;
		levels << ends;
		scores << ends;

		SetValue(txtHiName, 0, ChangeList);
		SetValue(txtHiScore, 0, ChangeList);
		SetValue(txtHiLevel, 0, ChangeList);
		//cerr << "names " << nstr << "levels " << levstr << "scores " << scostr;
//		DialogCmd DefaultCmds[] =
//			{
//	//{C_Label, lblMainMsg, 0,"X",NoList,CA_MainMsg,isSens,NoFrame, 0, 0},

//	{C_Frame, frmHiScore, 0,"",NoList,CA_None,isSens,NoFrame, 0, 0},
//	{C_Text, txtHiName, 0, "",nstr,
//	 CA_NoBorder, isSens, frmHiScore, 0, 0},
//	{C_Text, txtHiLevel, 0, "",levstr,
//	 CA_NoBorder, isSens, frmHiScore, txtHiName, 0},
//	{C_Text, txtHiScore, 0, "",scostr,
//	 CA_NoBorder, isSens, frmHiScore, txtHiLevel, 0},

//	//{C_Button, M_Cancel, 0, " Cancel ",NoList,CA_None,
//	//  isSens,NoFrame,0, lblMainMsg},
//	{C_Button, M_OK, 0, " OK ", NoList, CA_DefaultButton,
//			isSens, NoFrame, 0, frmHiScore},

//	//{C_Button, btnTestMDlg, 0, " Test ", NoList, CA_None,
//	//  isSens, NoFrame, M_OK, lblMainMsg},

//	{C_EndOfList,0,0,0,0,CA_None,0,0,0}
//		};

		UserDebug(Constructor,"wlnHiModalDialog::wlnHiModalDialog()\n")
		AddDialogCmds(DefaultCmds);		// add the predefined commands
	}

//===================>>> wlnHiModalDialog::~wlnHiModalDialog <<<====================
  wlnHiModalDialog::~wlnHiModalDialog()
  {
    UserDebug(Destructor,"wlnHiModalDialog::~wlnHiModalDialog() destructor\n")
  }

//====================>>> wlnHiModalDialog::wlnHiAction <<<====================
  int wlnHiModalDialog::wlnHiAction(char* msg)
  {
    ItemVal ans,rval;

//     SetString(txtHiName, names.str());
//     SetString(txtHiLevel, levels.str());
//     SetString(txtHiScore, scores.str());
    

		ans = ShowModalDialog(msg,rval);
//     delete names.str();
//     delete levels.str();
//     delete scores.str();
		if (ans == M_Cancel)
	return 0;

		// *** Add code to process dialog values here

		return ans == M_OK;
	}

//====================>>> wlnHiModalDialog::DialogCommand <<<====================
  void wlnHiModalDialog::DialogCommand(ItemVal id, ItemVal retval, CmdType ctype)
  {
    UserDebug2(CmdEvents,"wlnHiModalDialog::DialogCommand(id:%d, val:%d)\n",id, retval)

    switch (id)		// We will do some things depending on value
      {
	//@V@:Case: btnTestMDlg
	case btnTestMDlg:
	  {
	    vNoticeDialog note(this);
	    note.Notice("Test Dialog");
	    break;
	  }	//@V@:EndCase
      }

    vModalDialog::DialogCommand(id,retval,ctype);
  }

