//========================================================      -*-C++-*-
//@V@:Note: This file generated by vgen V1.02 (09:05:18 PM 18 Aug 1997).
//	wlhimdlg.h:	Header for wlnHiModalDialog class
//=======================================================================

////////////////////////////////////////////////////////////////////////////
// This file is a module in the program Zero Point, a video game program  //
// for Linux X11 and Windows.                                             //
//                                                                        //
// Copyright (C) 1996, 1997, 1998 by Enumerate Inc.                       //
//                                                                        //
// Enumerate Inc. can be contacted at enumerate@rocketmail.com            //
//                                                                        //
// This file is licensed within the terms of the GNU General Public       //
// License version 2 or later. This source code may freely redistributed  //
// or modified within the terms of that license, as described in the file //
// 'COPYING' which should be included with any redistribution of this     //
// file. If the file COPYING is not available, a copy of the General      //
// Public License can be obtained from the Free Software Foundation, Inc. //
// 675 Mass Ave., Cambridge, MA 02139.                                    //
//                                                                        //
// THIS PROGRAM IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER  //
// EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED       //
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.    //
// THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS    //
// WITH YOU.  SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF  //
// ALL NECESSARY SERVICING, REPAIR OR CORRECTION.                         //
//////////////////////////////////////////////////////////////////////////// 


#ifndef wlnHiMDLG_H
#define wlnHiMDLG_H

#include <v/vmodald.h>
#include "wlndefs.h"
enum {charSz= 512};

    class wlnHiModalDialog : public vModalDialog
      {
			public:		//---------------------------------------- public
	wlnHiModalDialog(vBaseWindow* bw, char* title = "High Scores");
	virtual ~wlnHiModalDialog();		// Destructor
	virtual void DialogCommand(ItemVal,ItemVal,CmdType); // action selected
	virtual int wlnHiAction(char* msg);

      protected:	//--------------------------------------- protected
//		char nstr[charSz];
//		char levstr[charSz];
//		char scostr[charSz];

      private:		//--------------------------------------- private

      };
#endif

