//=======================================================================
//@V@:Note: This file generated by vgen V1.02 (04:22:45 PM 04 Feb 1997).
//	wlnmdlg.cpp:	Source for wlnModalDialog class
//=======================================================================

////////////////////////////////////////////////////////////////////////////
// This file is a module in the program Zero Point, a video game program  //
// for Linux X11 and Windows.                                             //
//                                                                        //
// Copyright (C) 1996, 1997, 1998 by Enumerate Inc.                       //
//                                                                        //
// Enumerate Inc. can be contacted at enumerate@rocketmail.com            //
//                                                                        //
// This file is licensed within the terms of the GNU General Public       //
// License version 2 or later. This source code may freely redistributed  //
// or modified within the terms of that license, as described in the file //
// 'COPYING' which should be included with any redistribution of this     //
// file. If the file COPYING is not available, a copy of the General      //
// Public License can be obtained from the Free Software Foundation, Inc. //
// 675 Mass Ave., Cambridge, MA 02139.                                    //
//                                                                        //
// THIS PROGRAM IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER  //
// EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED       //
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.    //
// THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS    //
// WITH YOU.  SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF  //
// ALL NECESSARY SERVICING, REPAIR OR CORRECTION.                         //
//////////////////////////////////////////////////////////////////////////// 


#include "wlnmdlg.h"
#include "wlncmdw.h"
#include <v/vnotice.h>
#include "wlnapp.h"

//@V@:BeginIDs
    enum {
    lblMainMsg = 4500,
    btnTestMDlg,		// add your id's here
    
  };
//@V@:EndIds


static int lSpnMinMaxStp[3] = {1,97,3}; 

//@V@:BeginDialogCmd DefaultCmds
    static DialogCmd DefaultCmds[] =
      {
	{C_Label, lblMainMsg, 0,"X",NoList,CA_MainMsg,isSens,NoFrame, 0, 0},
	//	{C_Label, lblStartMsg, 0, startupwarn,NoList,CA_None,isSens,NoFrame,0,lblMainMsg},
	
	{C_Frame,pLFrame, 0, "", NoList, CA_None, isSens, NoFrame, 0, lblMainMsg},
	{C_Label,pLFLabel,0,"Pick a starting Level:",NoList,CA_NoBorder,isSens, pLFrame,0,0},
	{C_Spinner,lSpinner,1,"Level",(void*)lSpnMinMaxStp,CA_None,isSens,pLFrame,pLFLabel,0},
      /*{C_RadioButton, pickL1,1,"  1 ",NoList,CA_NoBorder,isSens,pLFrame,0,pLFLabel},
	{C_RadioButton, pickL4,0,"  4 ",NoList,CA_NoBorder,isSens,pLFrame,pickL1,pLFLabel},
	{C_RadioButton, pickL7,0,"  7 ",NoList,CA_NoBorder,isSens,pLFrame,pickL4,pLFLabel},
	{C_RadioButton, pickL10,0," 10 ",NoList,CA_NoBorder,isSens,pLFrame,pickL7,pLFLabel},
	{C_RadioButton, pickL13,0," 13 ",NoList,CA_NoBorder,isSens,pLFrame,0,pickL1},
	{C_RadioButton, pickL16,0," 16 ",NoList,CA_NoBorder,isSens,pLFrame,pickL13,pickL1},
	{C_RadioButton, pickL19,0," 19 ",NoList,CA_NoBorder,isSens,pLFrame,pickL16,pickL1},
	{C_RadioButton, pickL21,0," 21 ",NoList,CA_NoBorder,isSens,pLFrame,pickL19,pickL1},
        {C_RadioButton, pickL24,0," 24 ",NoList,CA_NoBorder,isSens,pLFrame,0,pickL13},
        {C_RadioButton, pickL27,0," 27 ",NoList,CA_NoBorder,isSens,pLFrame,pickL24,pickL13},
        {C_RadioButton, pickL30,0," 30 ",NoList,CA_NoBorder,isSens,pLFrame,pickL27,pickL13},
        {C_RadioButton, pickL33,0," 33 ",NoList,CA_NoBorder,isSens,pLFrame,pickL30,pickL13},
	*/
	//	{C_Button, M_Cancel, 0, " Cancel ",NoList,CA_None,
	//  isSens,NoFrame,0, pLFrame},
	{C_Button, M_OK, 0, " OK ", NoList, CA_DefaultButton,
	    isSens, NoFrame, 0, pLFrame},
	//	{C_Button, cancelStart, 0, " Cancel ", NoList, CA_None, isSens, NoFrame, M_OK, pLFrame},
	//{C_Button, btnTestMDlg, 0, " Test ", NoList, CA_None,
	//  isSens, NoFrame, M_OK, pLFrame},

	{C_EndOfList,0,0,0,0,CA_None,0,0,0}
    };
//@V@:EndDialogCmd


//======================>>> wlnModalDialog::wlnModalDialog <<<==================
  wlnModalDialog::wlnModalDialog(vBaseWindow* bw, char* title) :
    vModalDialog(bw, title)
  {
    UserDebug(Constructor,"wlnModalDialog::wlnModalDialog()\n")
    _myCmdWin = (wlnCmdWindow*) bw;
    AddDialogCmds(DefaultCmds);		// add the predefined commands
  }

//===================>>> wlnModalDialog::~wlnModalDialog <<<====================
  wlnModalDialog::~wlnModalDialog()
  {
    UserDebug(Destructor,"wlnModalDialog::~wlnModalDialog() destructor\n")
  }

//====================>>> wlnModalDialog::wlnAction <<<====================
  int wlnModalDialog::wlnAction(char* msg)
  {
    ItemVal ans,rval;

    ans = ShowModalDialog(msg,rval);
    if (ans == M_Cancel)
	return 0;

    // *** Add code to process dialog values here

    return ans == M_OK;
  }//wlnAction

//====================>>> wlnModalDialog::DialogCommand <<<====================
void wlnModalDialog::DialogCommand(ItemVal id, ItemVal retval, CmdType ctype){
  UserDebug2(CmdEvents,"wlnModalDialog::DialogCommand(id:%d, val:%d)\n",id, retval);
  //  static int nexttime = 0;
  //if(!nexttime++){
  //  SetValue(cancelStart, True, Hidden);
  //  SetValue(lblStartMsg, True, Hidden);
  //}
  int theLevel;
  //int i;
  //ItemVal indx;
  switch (id)		// We will do some things depending on value
    {
    case M_OK:
      //theLevel = 0;
      //indx = pickL1;
      //for(i = 0; i < 12; i++){
      //if(GetValue(pickL1 + i)){
      //theLevel = i * 3 + 1;
      //}
      //}
      theLevel = GetValue(lSpinner);
      if(!theLevel) theLevel = 1;
      ((wlnApp*)theApp)->startAtLevel(theLevel);
      break;
    case btnTestMDlg:
      {
	vNoticeDialog note(this);
	note.Notice("Test Dialog");
	break;
      }	//@V@:EndCase
    case cancelStart:
      {
	((wlnApp*)theApp)->Exit();
      }
    }//end switch
  vModalDialog::DialogCommand(id,retval,ctype);
}//DialogCommand

