//=======================================================================
//@V@:Note: This file generated by vgen V1.02 (11:40:19 PM 15 Apr 1997).
//	wlnynmdlg.cpp:	Source for wlnYNDialogModalDialog class
//=======================================================================

////////////////////////////////////////////////////////////////////////////
// This file is a module in the program Zero Point, a video game program  //
// for Linux X11 and Windows.                                             //
//                                                                        //
// Copyright (C) 1996, 1997, 1998 by Enumerate Inc.                       //
//                                                                        //
// Enumerate Inc. can be contacted at enumerate@rocketmail.com            //
//                                                                        //
// This file is licensed within the terms of the GNU General Public       //
// License version 2 or later. This source code may freely redistributed  //
// or modified within the terms of that license, as described in the file //
// 'COPYING' which should be included with any redistribution of this     //
// file. If the file COPYING is not available, a copy of the General      //
// Public License can be obtained from the Free Software Foundation, Inc. //
// 675 Mass Ave., Cambridge, MA 02139.                                    //
//                                                                        //
// THIS PROGRAM IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER  //
// EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED       //
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.    //
// THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS    //
// WITH YOU.  SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF  //
// ALL NECESSARY SERVICING, REPAIR OR CORRECTION.                         //
//////////////////////////////////////////////////////////////////////////// 


#include "wlnynmdg.h"
#include <v/vnotice.h>

//@V@:BeginIDs
    enum {
    lblMainMsg = 5000,
    btnTestMDlg		// add your id's here
  };
//@V@:EndIds

//@V@:BeginDialogCmd DefaultCmds
    static DialogCmd DefaultCmds[] =
      {
	{C_Text, lblMainMsg, 0,"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\nW\nW\nW\nW",NoList,CA_NoBorder,isSens,NoFrame, 0, 0},

	{C_Button, M_Yes, 0, " Yes ", NoList, CA_DefaultButton,
	    isSens, NoFrame, 0, lblMainMsg},

	{C_Button, M_No, 0, " No ",NoList,CA_None,
	    isSens,NoFrame,M_Yes, lblMainMsg},

	{C_Button, M_Cancel, 0, " Cancel ",NoList,CA_None,
	    isSens,NoFrame,M_No, lblMainMsg},

	{C_EndOfList,0,0,0,0,CA_None,0,0,0}
    };
//@V@:EndDialogCmd


//======================>>> wlnYNDialog::wlnYNDialog <<<==================
  wlnYNDialog::wlnYNDialog(vBaseWindow* bw, char* title) :
    vModalDialog(bw, title)
  {
		UserDebug(Constructor,"wlnYNDialog::wlnYNDialog()\n")
		_addedCmds = 0;
    //DefaultCmds[0].title = title;
		//AddDialogCmds(DefaultCmds);		// add the predefined commands
  }

//===================>>> wlnYNDialog::~wlnYNDialog <<<====================
  wlnYNDialog::~wlnYNDialog()
  {
    UserDebug(Destructor,"wlnYNDialog::~wlnYNDialog() destructor\n")
  }

//====================>>> wlnYNDialog::wlnYNDialogAction <<<====================
  int wlnYNDialog::wlnYNDialogAction(char* msg)
  {
		ItemVal ans,rval;
		int flag = 0;
		ans = ShowModalDialog(msg,rval);
    if (ans == M_Cancel)
			flag = 0;
    if(ans == M_No)
			flag = -1;

    // *** Add code to process dialog values here
    if(ans == M_Yes)
			flag = 1;
    return flag;
  }

int wlnYNDialog::AskYN(char* questn){
		DefaultCmds[0].title = questn;
		if(!_addedCmds++){
			AddDialogCmds(DefaultCmds);
		}
	//SetString(lblMainMsg, questn);
	return wlnYNDialogAction(questn);
}

//====================>>> wlnYNDialog::DialogCommand <<<====================
	void wlnYNDialog::DialogCommand(ItemVal id, ItemVal retval, CmdType ctype)
	{
    UserDebug2(CmdEvents,"wlnYNDialog::DialogCommand(id:%d, val:%d)\n",id, retval)


    vModalDialog::DialogCommand(id,retval,ctype);
    if (id == M_Yes || id == M_No)
        CloseDialog();
  }


















































